services:
  prometheus-grafana-test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - pgt

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - pgt

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - pgt
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  pgt:
    driver: bridge